-- Inserir banners de exemplo
INSERT INTO public.banners (
  titulo, tipo_conteudo, layout_banner, midia_url, midia_tipo, 
  data_inicio, data_fim, status, ordem, 
  texto_botao, url_acao, planos_permitidos,
  visualizacoes, cliques, tempo_total_reproducao
) VALUES 
(
  'Jogo da Final - Ao Vivo Agora', 
  'live_agora', 
  'hero_cta', 
  '/lovable-uploads/178882be-43bc-492f-ab1c-036716604bc1.png', 
  'image',
  NOW() - INTERVAL '1 hour',
  NOW() + INTERVAL '2 hours',
  true,
  1,
  'Assistir Agora',
  '/live/final-championship',
  '{"gratuito", "basico", "premium", "vip"}',
  15420,
  892,
  45600
),
(
  'Semifinal - Hoje às 20h', 
  'live_programado', 
  'video_texto', 
  '/lovable-uploads/3e4f7302-40a3-4b04-95b2-f925cfb43250.png', 
  'image',
  NOW() + INTERVAL '6 hours',
  NOW() + INTERVAL '8 hours',
  true,
  2,
  'Lembrar-me',
  '/schedule/semifinal',
  '{"basico", "premium", "vip"}',
  8930,
  445,
  0
),
(
  'Melhores Momentos da Rodada', 
  'vod', 
  'imagem_botao', 
  '/lovable-uploads/56b1b2ee-687f-4828-8038-c0902cb9f932.png', 
  'image',
  NOW() - INTERVAL '2 days',
  NOW() + INTERVAL '5 days',
  true,
  3,
  'Ver Vídeo',
  '/videos/melhores-momentos-rodada-15',
  '{"gratuito", "basico", "premium", "vip"}',
  12340,
  678,
  89400
),
(
  'Campanha Black Friday - 50% OFF', 
  'campanha', 
  'hero_cta', 
  '/lovable-uploads/68bd6b68-c5e2-4cdc-81bb-941708e88ddb.png', 
  'image',
  NOW() - INTERVAL '1 day',
  NOW() + INTERVAL '7 days',
  true,
  4,
  'Aproveitar Oferta',
  '/campaigns/black-friday-2024',
  '{"gratuito", "basico"}',
  25670,
  1892,
  0
),
(
  'Novo Documentário: História do Clube', 
  'recomendado', 
  'video_texto', 
  '/lovable-uploads/736ea3c4-4ba8-4dd3-84ef-adbda2ce6750.png', 
  'video',
  NOW() - INTERVAL '3 days',
  NOW() + INTERVAL '10 days',
  true,
  5,
  'Assistir Trailer',
  '/videos/documentario-historia-clube',
  '{"premium", "vip"}',
  5670,
  234,
  67800
),
(
  'Banner Institucional - Novos Valores', 
  'institucional', 
  'mini_card', 
  '/lovable-uploads/7ec692e9-77df-4673-90f4-ed298d10760f.png', 
  'image',
  NOW() - INTERVAL '1 week',
  NOW() + INTERVAL '1 month',
  true,
  6,
  'Saiba Mais',
  '/about/novos-valores',
  '{"gratuito", "basico", "premium", "vip"}',
  3450,
  123,
  0
),
(
  'Entrevista Exclusiva com o Técnico', 
  'vod', 
  'imagem_botao', 
  '/lovable-uploads/a945b2ac-8b16-4c57-a844-122cc1e8170c.png', 
  'video',
  NOW() - INTERVAL '5 days',
  NOW() + INTERVAL '3 days',
  true,
  7,
  'Ver Entrevista',
  '/videos/entrevista-tecnico-dezembro',
  '{"basico", "premium", "vip"}',
  8920,
  445,
  123600
),
(
  'Promoção: Ingresso + Camisa', 
  'campanha', 
  'hero_cta', 
  '/lovable-uploads/b178263a-95eb-4d88-ad87-aa9de585a258.png', 
  'image',
  NOW() + INTERVAL '1 day',
  NOW() + INTERVAL '2 weeks',
  false,
  8,
  'Comprar Combo',
  '/campaigns/combo-ingresso-camisa',
  '{"gratuito", "basico", "premium"}',
  0,
  0,
  0
),
(
  'Live de Análise Pós-Jogo', 
  'live_programado', 
  'video_texto', 
  '/lovable-uploads/c77a6a4a-5568-4a9c-bdcc-34a53dca4782.png', 
  'image',
  NOW() + INTERVAL '3 hours',
  NOW() + INTERVAL '5 hours',
  true,
  9,
  'Participar',
  '/live/analise-pos-jogo',
  '{"premium", "vip"}',
  2340,
  89,
  0
),
(
  'Top 10 Gols da Temporada', 
  'recomendado', 
  'mini_card', 
  '/lovable-uploads/d5035e4b-b98c-4f58-a0b5-6c9da2398ab0.png', 
  'video',
  NOW() - INTERVAL '1 week',
  NOW() + INTERVAL '2 weeks',
  true,
  10,
  'Ver Ranking',
  '/videos/top-10-gols-temporada',
  '{"gratuito", "basico", "premium", "vip"}',
  18930,
  923,
  234500
);