// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prioqbtnxxygqxrfjcqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByaW9xYnRueHh5Z3F4cmZqY3FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MTQ1NTgsImV4cCI6MjA2ODA5MDU1OH0.TTfJf-X2wlYeV4CwZ0nsCUwcDr2ngsODgD0eYzCaHZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});